import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/services/scss/globals.scss";
import { GlobalProvider } from "@/services/contexts/global-context";
import MainNav from "@/components/main-nav/MainNav";
import ScrollToTop from "@/components/main-nav/scroll-to-top";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DHSC 2k17",
  description: "Generated by Abu Hasan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GlobalProvider>
        <body className={inter.className}>
          <header id="main_header">
            <MainNav />
          </header>
          {children}
          <ScrollToTop />
        </body>
      </GlobalProvider>
    </html>
  );
}
